import type {
  ActionPriority,
  DimensionId,
  EffortLevel,
  EvidenceId,
  FindingId,
  RecommendationId,
  RiskId,
} from "./primitives";

/**
 * An actionable next step derived from Risks and Findings.
 * Generated by the Insight Engine pipeline and ranked by priorityScore.
 */
export interface Recommendation {
  id: RecommendationId;
  title: string;
  description: string;
  dimensionId: DimensionId;
  dimension: string;
  riskIds: RiskId[];
  evidenceIds: EvidenceId[];
  priority: ActionPriority;
  effort: EffortLevel;
  confidence: number;
  estimatedScoreImprovement: number;
  rationale: string;
  nextSteps: string[];
  /** Ranking score used for ordering (higher = more urgent). */
  priorityScore: number;
  /** @deprecated Prefer `evidenceIds` — kept for UI adapters. */
  supportingEvidenceIds: EvidenceId[];
  findingIds: FindingId[];
  /** @deprecated Prefer `estimatedScoreImprovement` — kept for UI adapters. */
  estimatedHealthImpact: number;
}
