import type {
  ActionPriority,
  DimensionId,
  EvidenceId,
  FindingId,
  RecommendationId,
} from "./primitives";

/**
 * An actionable next step derived from Risks and Findings.
 * Generated by the Insight Engine pipeline.
 */
export interface Recommendation {
  id: RecommendationId;
  title: string;
  priority: ActionPriority;
  dimensionId: DimensionId;
  dimension: string;
  description: string;
  /** Supporting evidence documents */
  supportingEvidenceIds: EvidenceId[];
  /** Findings that motivated this recommendation */
  findingIds: FindingId[];
  confidence: number;
  estimatedHealthImpact: number;
}
