import { COMPANY_LIFECYCLE_STAGES } from "@/lib/domain/company-classification";
import { definePlaybook } from "../base";

export const acquireACompanyPlaybook = definePlaybook({
  id: "acquire-a-company",
  name: "Acquire a Company",
  objective:
    "Structure buy-side diligence around downside risk, quality of earnings, and integration complexity.",
  successCriteria: [
    "Target financial quality is evidence-backed",
    "Legal and IP exposure is scoped",
    "Customer concentration and contracts are understood",
    "Integration and key-person risks are flagged",
  ],
  focusAreas: [
    "Downside risk",
    "Quality of earnings",
    "Customer concentration",
    "Legal liabilities",
    "Security",
    "Integration complexity",
    "Key-person risk",
    "Synergies",
    "Purchase-price risk",
  ],
  applicableLifecycleStages: [...COMPANY_LIFECYCLE_STAGES],
  minCoveragePercent: 25,
  executiveSummaryGuidance: [
    "Lead with downside risk and quality of earnings.",
    "Surface key-person and integration complexity early.",
  ],
  dimensionPriorities: [
    { dimensionId: "dim-financial", weight: 1, rationale: "Valuation and QoE." },
    { dimensionId: "dim-legal", weight: 0.95, rationale: "Hidden liabilities." },
    { dimensionId: "dim-customer", weight: 0.9, rationale: "Revenue durability." },
    { dimensionId: "dim-people", weight: 0.85, rationale: "Integration risk." },
    { dimensionId: "dim-security", weight: 0.8, rationale: "Inherited security risk." },
    { dimensionId: "dim-governance", weight: 0.75, rationale: "Authority and controls." },
  ],
  questionPriorities: [
    { questionId: "q-fin-fund-operations", weight: 1.4, rationale: "Target continuity." },
    { questionId: "q-fin-recurring-healthy", weight: 1.35, rationale: "QoE." },
    { questionId: "q-legal-customer-contracts", weight: 1.35, rationale: "Transfer risk." },
    { questionId: "q-legal-ip-assignments", weight: 1.3, rationale: "Asset ownership." },
    { questionId: "q-cust-concentration", weight: 1.3, rationale: "Deal risk." },
    { questionId: "q-people-key-person", weight: 1.3, rationale: "Integration." },
    { questionId: "q-sec-policies", weight: 1.2, rationale: "Inherited security." },
    { questionId: "q-ops-financial-controls", weight: 1.2, rationale: "Control environment." },
    { questionId: "q-gov-board-approvals", weight: 1.1, rationale: "Deal authority." },
  ],
  requiredEvidence: [
    {
      evidenceType: "financial_statements",
      label: "Target financials",
      why: "Buy-side QoE baseline.",
      level: "required",
      category: "financial",
    },
    {
      evidenceType: "customer_contracts",
      label: "Customer contracts",
      why: "Revenue transferability.",
      level: "required",
      category: "legal",
    },
  ],
  recommendedEvidence: [
    {
      evidenceType: "ip_assignments",
      label: "IP documentation",
      why: "Asset diligence.",
      level: "recommended",
      category: "legal",
    },
    {
      evidenceType: "org_chart",
      label: "Org / key person map",
      why: "Integration planning.",
      level: "recommended",
      category: "people",
    },
    {
      evidenceType: "security_policies",
      label: "Security pack",
      why: "Inherited security liabilities.",
      level: "recommended",
      category: "security",
    },
  ],
  reportSections: [
    "Acquisition thesis",
    "Downside risk",
    "Quality of earnings",
    "Legal & IP",
    "Customers",
    "People & integration",
    "Open diligence",
  ],
  recommendationOrdering: [
    { theme: "financial", weight: 1.3, rationale: "Purchase-price risk." },
    { theme: "legal", weight: 1.3, rationale: "Liability risk." },
    { theme: "customer", weight: 1.2, rationale: "Concentration." },
    { theme: "people", weight: 1.2, rationale: "Key-person / integration." },
    { theme: "security", weight: 1.15, rationale: "Inherited risk." },
  ],
  recommendationDimensionWeights: {
    "dim-financial": 1.3,
    "dim-legal": 1.3,
    "dim-customer": 1.2,
    "dim-people": 1.2,
    "dim-security": 1.15,
  },
  uploadCatalog: [
    {
      id: "upload-target-financials",
      label: "Target financial statements",
      evidenceCategory: "financial",
      why: "Buy-side QoE and purchase-price risk.",
      level: "required",
      priority: 100,
      evidenceTypes: ["financial_statements"],
      questionsItCouldAnswer: [
        "q-fin-fund-operations",
        "q-fin-recurring-healthy",
        "q-ops-financial-controls",
      ],
      expectedCoverageImpact: 0.15,
      applicableStages: [...COMPANY_LIFECYCLE_STAGES],
    },
    {
      id: "upload-target-contracts",
      label: "Customer contract inventory",
      evidenceCategory: "legal",
      why: "Revenue diligence and concentration.",
      level: "required",
      priority: 95,
      evidenceTypes: ["customer_contracts"],
      questionsItCouldAnswer: [
        "q-legal-customer-contracts",
        "q-cust-concentration",
      ],
      expectedCoverageImpact: 0.12,
      applicableStages: [...COMPANY_LIFECYCLE_STAGES],
    },
    {
      id: "upload-target-ip",
      label: "IP / assignment pack",
      evidenceCategory: "legal",
      why: "Asset ownership checks.",
      level: "recommended",
      priority: 80,
      evidenceTypes: ["ip_assignments"],
      questionsItCouldAnswer: ["q-legal-ip-assignments"],
      expectedCoverageImpact: 0.1,
      applicableStages: [...COMPANY_LIFECYCLE_STAGES],
    },
  ],
});
