import { COMPANY_LIFECYCLE_STAGES } from "@/lib/domain/company-classification";
import { definePlaybook } from "../base";

export const annualAuditPlaybook = definePlaybook({
  id: "annual-audit",
  name: "Annual Audit",
  objective:
    "Align evidence with audit readiness: statements, reconciliations, controls, and supporting schedules.",
  successCriteria: [
    "Financial statements are complete and reconcilable",
    "Financial controls evidence is available",
    "Supporting schedules cover payroll, tax, and debt",
    "Open audit PBC items are tracked",
  ],
  focusAreas: [
    "Financial statements",
    "Reconciliations",
    "Controls",
    "Revenue recognition",
    "Payroll",
    "Tax",
    "Debt",
    "Supporting schedules",
    "Audit readiness",
  ],
  applicableLifecycleStages: [
    "Early Revenue",
    "Product-Market Fit",
    "Growth",
    "Scale",
    "Exit Ready",
  ],
  minCoveragePercent: 30,
  executiveSummaryGuidance: [
    "Lead with financial statements, reconciliations, and controls.",
    "Track PBC open items explicitly.",
  ],
  dimensionPriorities: [
    { dimensionId: "dim-financial", weight: 1, rationale: "Reporting package." },
    { dimensionId: "dim-operations", weight: 0.95, rationale: "Control environment." },
    { dimensionId: "dim-legal", weight: 0.85, rationale: "Support agreements." },
    { dimensionId: "dim-governance", weight: 0.8, rationale: "Oversight." },
  ],
  questionPriorities: [
    { questionId: "q-ops-financial-controls", weight: 1.5, rationale: "Control testing." },
    { questionId: "q-fin-fund-operations", weight: 1.3, rationale: "Going concern." },
    { questionId: "q-fin-recurring-healthy", weight: 1.25, rationale: "Revenue recognition." },
    { questionId: "q-legal-employment-agreements", weight: 1.25, rationale: "Payroll / people." },
    { questionId: "q-gov-board-approvals", weight: 1.2, rationale: "Approval evidence." },
    { questionId: "q-ops-process-ownership", weight: 1.1, rationale: "Control owners." },
  ],
  requiredEvidence: [
    {
      evidenceType: "financial_statements",
      label: "Financial statements",
      why: "Audit reporting baseline.",
      level: "required",
      category: "financial",
    },
    {
      evidenceType: "financial_controls",
      label: "Financial controls documentation",
      why: "Control testing support.",
      level: "required",
      category: "operations",
    },
  ],
  recommendedEvidence: [
    {
      evidenceType: "employment_agreements",
      label: "Employment agreements",
      why: "Payroll / people process evidence.",
      level: "recommended",
      category: "legal",
    },
    {
      evidenceType: "board_minutes",
      label: "Board approvals",
      why: "Governance evidence for auditors.",
      level: "recommended",
      category: "governance",
    },
  ],
  reportSections: [
    "Audit readiness",
    "Financial statements",
    "Controls",
    "PBC open items",
    "Supporting schedules",
    "Next uploads",
  ],
  recommendationOrdering: [
    { theme: "control", weight: 1.4, rationale: "Audit testing." },
    { theme: "financial", weight: 1.3, rationale: "Reporting pack." },
    { theme: "audit", weight: 1.25, rationale: "PBC closeout." },
    { theme: "employment", weight: 1.15, rationale: "Support docs." },
  ],
  recommendationDimensionWeights: {
    "dim-operations": 1.3,
    "dim-financial": 1.25,
    "dim-legal": 1.1,
    "dim-governance": 1.1,
  },
  uploadCatalog: [
    {
      id: "upload-financials-audit",
      label: "Audited / draft financial statements",
      evidenceCategory: "financial",
      why: "Reporting package for the audit.",
      level: "required",
      priority: 100,
      evidenceTypes: ["financial_statements"],
      questionsItCouldAnswer: [
        "q-fin-fund-operations",
        "q-fin-recurring-healthy",
      ],
      expectedCoverageImpact: 0.15,
      applicableStages: [
        "Early Revenue",
        "Product-Market Fit",
        "Growth",
        "Scale",
        "Exit Ready",
      ],
    },
    {
      id: "upload-controls-docs",
      label: "Financial controls documentation",
      evidenceCategory: "operations",
      why: "PBC and control testing.",
      level: "required",
      priority: 98,
      evidenceTypes: ["financial_controls"],
      questionsItCouldAnswer: ["q-ops-financial-controls"],
      expectedCoverageImpact: 0.12,
      applicableStages: [
        "Early Revenue",
        "Product-Market Fit",
        "Growth",
        "Scale",
        "Exit Ready",
      ],
    },
    {
      id: "upload-employment-audit",
      label: "Employment agreements sample",
      evidenceCategory: "legal",
      why: "Payroll and people process evidence.",
      level: "recommended",
      priority: 75,
      evidenceTypes: ["employment_agreements"],
      questionsItCouldAnswer: ["q-legal-employment-agreements"],
      expectedCoverageImpact: 0.08,
      applicableStages: [...COMPANY_LIFECYCLE_STAGES],
    },
  ],
});
