import { COMPANY_LIFECYCLE_STAGES } from "@/lib/domain/company-classification";
import { definePlaybook } from "../base";

export const boardReadinessPlaybook = definePlaybook({
  id: "board-readiness",
  name: "Board Readiness",
  objective:
    "Focus on board cadence, minutes, approvals, financial reporting, and management accountability.",
  successCriteria: [
    "Board meeting cadence is evidenced",
    "Material approvals and written consents are documented",
    "Financial reporting pack is board-ready",
    "Unresolved risks and decisions are visible",
  ],
  focusAreas: [
    "Board cadence",
    "Minutes",
    "Written consents",
    "Approval history",
    "Financial reporting",
    "Strategic decisions",
    "Unresolved risks",
    "Management accountability",
  ],
  applicableLifecycleStages: [
    "Early Revenue",
    "Product-Market Fit",
    "Growth",
    "Scale",
    "Exit Ready",
  ],
  minCoveragePercent: 25,
  executiveSummaryGuidance: [
    "Board operating system first: cadence, minutes, consents, approvals.",
    "Surface unresolved risks and decisions lacking evidence.",
  ],
  dimensionPriorities: [
    { dimensionId: "dim-governance", weight: 1, rationale: "Board operating system." },
    { dimensionId: "dim-financial", weight: 0.85, rationale: "Board numbers." },
    { dimensionId: "dim-legal", weight: 0.8, rationale: "Authority and filings." },
    { dimensionId: "dim-operations", weight: 0.7, rationale: "KPI pack." },
  ],
  questionPriorities: [
    { questionId: "q-gov-cadence", weight: 1.5, rationale: "Meeting rhythm." },
    { questionId: "q-gov-board-approvals", weight: 1.45, rationale: "Authority trail." },
    { questionId: "q-gov-cap-table", weight: 1.35, rationale: "Ownership for board." },
    { questionId: "q-gov-equity-issuances", weight: 1.3, rationale: "Equity actions." },
    { questionId: "q-ops-kpi-monitoring", weight: 1.2, rationale: "Board KPIs." },
    { questionId: "q-fin-fund-operations", weight: 1.15, rationale: "Cash for board." },
    { questionId: "q-people-org-clarity", weight: 1.1, rationale: "Accountability." },
  ],
  requiredEvidence: [
    {
      evidenceType: "board_minutes",
      label: "Board minutes / packs",
      why: "Cadence and approvals evidence.",
      level: "required",
      category: "governance",
    },
  ],
  recommendedEvidence: [
    {
      evidenceType: "cap_table",
      label: "Cap table",
      why: "Equity clarity for the board.",
      level: "recommended",
      category: "governance",
    },
    {
      evidenceType: "financial_statements",
      label: "Board financials",
      why: "Numbers for decisions.",
      level: "recommended",
      category: "financial",
    },
  ],
  reportSections: [
    "Board readiness",
    "Cadence & approvals",
    "Cap table & equity",
    "Board pack gaps",
    "Unresolved risks",
    "Next uploads",
  ],
  recommendationOrdering: [
    { theme: "board", weight: 1.4, rationale: "Governance first." },
    { theme: "approval", weight: 1.35, rationale: "Authority trail." },
    { theme: "cap table", weight: 1.25, rationale: "Ownership hygiene." },
    { theme: "kpi", weight: 1.15, rationale: "Decision inputs." },
  ],
  recommendationDimensionWeights: {
    "dim-governance": 1.4,
    "dim-financial": 1.1,
    "dim-legal": 1.1,
  },
  uploadCatalog: [
    {
      id: "upload-board-minutes",
      label: "Board minutes",
      evidenceCategory: "governance",
      why: "Prove cadence, minutes, and approvals.",
      level: "required",
      priority: 100,
      evidenceTypes: ["board_minutes"],
      questionsItCouldAnswer: ["q-gov-cadence", "q-gov-board-approvals"],
      expectedCoverageImpact: 0.15,
      applicableStages: [
        "Early Revenue",
        "Product-Market Fit",
        "Growth",
        "Scale",
        "Exit Ready",
      ],
    },
    {
      id: "upload-board-pack",
      label: "Latest board pack",
      evidenceCategory: "governance",
      why: "Completeness for the next meeting.",
      level: "required",
      priority: 95,
      evidenceTypes: ["board_minutes", "financial_statements"],
      questionsItCouldAnswer: [
        "q-gov-cadence",
        "q-fin-fund-operations",
        "q-ops-kpi-monitoring",
      ],
      expectedCoverageImpact: 0.12,
      applicableStages: [
        "Early Revenue",
        "Product-Market Fit",
        "Growth",
        "Scale",
        "Exit Ready",
      ],
    },
    {
      id: "upload-cap-table-board",
      label: "Cap table",
      evidenceCategory: "governance",
      why: "Equity clarity for directors.",
      level: "recommended",
      priority: 80,
      evidenceTypes: ["cap_table"],
      questionsItCouldAnswer: ["q-gov-cap-table", "q-gov-equity-issuances"],
      expectedCoverageImpact: 0.1,
      applicableStages: [...COMPANY_LIFECYCLE_STAGES],
    },
  ],
});
