import { COMPANY_LIFECYCLE_STAGES } from "@/lib/domain/company-classification";
import { definePlaybook } from "../base";

export const enterpriseSalesPlaybook = definePlaybook({
  id: "enterprise-sales",
  name: "Enterprise Sales",
  objective:
    "Prioritize security, privacy, availability, incident response, and vendor diligence for enterprise deals.",
  successCriteria: [
    "Security policies are current and evidenced",
    "Incident response is documented",
    "Critical controls are demonstrable",
    "Vendor diligence pack is ready for enterprise buyers",
  ],
  focusAreas: [
    "Security",
    "Privacy",
    "Availability",
    "Incident response",
    "Vendor diligence",
    "Insurance",
    "Data handling",
    "Business continuity",
  ],
  applicableLifecycleStages: [...COMPANY_LIFECYCLE_STAGES],
  minCoveragePercent: 20,
  executiveSummaryGuidance: [
    "Enterprise deals gate on security, privacy, and IR evidence.",
    "Prioritize vendor diligence artifacts that unblock questionnaires.",
  ],
  dimensionPriorities: [
    { dimensionId: "dim-security", weight: 1, rationale: "Enterprise gate." },
    { dimensionId: "dim-legal", weight: 0.85, rationale: "Contractual commitments." },
    { dimensionId: "dim-operations", weight: 0.8, rationale: "Availability / continuity." },
    { dimensionId: "dim-customer", weight: 0.75, rationale: "Customer proof." },
    { dimensionId: "dim-governance", weight: 0.7, rationale: "Policy ownership." },
  ],
  questionPriorities: [
    { questionId: "q-sec-policies", weight: 1.5, rationale: "Policy baseline." },
    { questionId: "q-sec-critical-controls", weight: 1.5, rationale: "Control proof." },
    { questionId: "q-sec-incident-response", weight: 1.4, rationale: "IR readiness." },
    { questionId: "q-legal-customer-contracts", weight: 1.2, rationale: "MSA / DPA terms." },
    { questionId: "q-ops-process-ownership", weight: 1.1, rationale: "Continuity ownership." },
    { questionId: "q-cust-nrr", weight: 1.05, rationale: "Customer health proof." },
  ],
  requiredEvidence: [
    {
      evidenceType: "security_policies",
      label: "Security policies",
      why: "Enterprise security review.",
      level: "required",
      category: "security",
    },
    {
      evidenceType: "incident_response",
      label: "Incident response plan",
      why: "Buyer IR diligence.",
      level: "required",
      category: "security",
    },
  ],
  recommendedEvidence: [
    {
      evidenceType: "soc2",
      label: "SOC 2 / trust report",
      why: "Accelerates vendor review.",
      level: "recommended",
      category: "security",
    },
    {
      evidenceType: "mfa_coverage",
      label: "Critical controls evidence",
      why: "MFA and control proof.",
      level: "recommended",
      category: "security",
    },
  ],
  reportSections: [
    "Enterprise readiness",
    "Security & privacy",
    "Availability & IR",
    "Vendor diligence pack",
    "Open questionnaires",
    "Next uploads",
  ],
  recommendationOrdering: [
    { theme: "security", weight: 1.45, rationale: "Deal blocker." },
    { theme: "incident", weight: 1.35, rationale: "IR pack." },
    { theme: "privacy", weight: 1.3, rationale: "DPA / privacy." },
    { theme: "control", weight: 1.25, rationale: "Critical controls." },
    { theme: "vendor", weight: 1.2, rationale: "Questionnaire speed." },
  ],
  recommendationDimensionWeights: {
    "dim-security": 1.4,
    "dim-legal": 1.15,
    "dim-operations": 1.1,
  },
  uploadCatalog: [
    {
      id: "upload-soc2",
      label: "SOC 2",
      evidenceCategory: "security",
      why: "Fastest path through enterprise security review.",
      level: "required",
      priority: 100,
      evidenceTypes: ["soc2"],
      questionsItCouldAnswer: ["q-sec-policies", "q-sec-critical-controls"],
      expectedCoverageImpact: 0.15,
      applicableStages: [...COMPANY_LIFECYCLE_STAGES],
    },
    {
      id: "upload-security-policies",
      label: "Security policies",
      evidenceCategory: "security",
      why: "Baseline for vendor questionnaires.",
      level: "required",
      priority: 98,
      evidenceTypes: ["security_policies"],
      questionsItCouldAnswer: ["q-sec-policies"],
      expectedCoverageImpact: 0.12,
      applicableStages: [...COMPANY_LIFECYCLE_STAGES],
    },
    {
      id: "upload-incident-response",
      label: "Incident response",
      evidenceCategory: "security",
      why: "Required IR diligence artifact.",
      level: "required",
      priority: 96,
      evidenceTypes: ["incident_response"],
      questionsItCouldAnswer: ["q-sec-incident-response"],
      expectedCoverageImpact: 0.1,
      applicableStages: [...COMPANY_LIFECYCLE_STAGES],
    },
  ],
});
