import { definePlaybook } from "../base";

export const ipoReadinessPlaybook = definePlaybook({
  id: "ipo-readiness",
  name: "IPO Readiness",
  objective:
    "Track public-company readiness: controls, governance, audit, compliance, and disclosure.",
  successCriteria: [
    "Financial reporting and controls are IPO-grade",
    "Governance cadence and board practices are mature",
    "Security and compliance evidence is sustained",
    "Audit readiness is continuous, not episodic",
  ],
  focusAreas: [
    "Controls",
    "Governance",
    "Audit quality",
    "Compliance",
    "Financial reporting",
    "Disclosure readiness",
    "Security",
    "Board independence",
    "Operating maturity",
  ],
  // Idea-stage companies should not be failed against IPO bars under other playbooks;
  // this playbook itself only fully applies from Growth onward.
  applicableLifecycleStages: ["Growth", "Scale", "Exit Ready"],
  minCoveragePercent: 35,
  executiveSummaryGuidance: [
    "IPO readiness requires sustained controls, governance, and disclosure maturity.",
    "Do not treat early-stage gaps as IPO failures when the company is not in scope.",
  ],
  dimensionPriorities: [
    { dimensionId: "dim-governance", weight: 1, rationale: "Public-company board practices." },
    { dimensionId: "dim-financial", weight: 0.95, rationale: "Reporting quality." },
    { dimensionId: "dim-operations", weight: 0.9, rationale: "Control environment." },
    { dimensionId: "dim-security", weight: 0.85, rationale: "Compliance posture." },
    { dimensionId: "dim-legal", weight: 0.8, rationale: "Disclosure readiness." },
  ],
  questionPriorities: [
    { questionId: "q-ops-financial-controls", weight: 1.5, rationale: "SOX-adjacent controls." },
    { questionId: "q-gov-cadence", weight: 1.4, rationale: "Board maturity." },
    { questionId: "q-gov-board-approvals", weight: 1.35, rationale: "Formal authority." },
    { questionId: "q-sec-policies", weight: 1.3, rationale: "Compliance baseline." },
    { questionId: "q-sec-critical-controls", weight: 1.25, rationale: "Control proof." },
    { questionId: "q-gov-cap-table", weight: 1.2, rationale: "Capitalization clarity." },
    { questionId: "q-fin-revenue-growing", weight: 1.15, rationale: "Reporting story." },
    { questionId: "q-legal-customer-contracts", weight: 1.1, rationale: "Disclosure risk." },
  ],
  requiredEvidence: [
    {
      evidenceType: "financial_controls",
      label: "Financial controls",
      why: "Public-company control baseline.",
      level: "required",
      category: "operations",
    },
    {
      evidenceType: "board_minutes",
      label: "Board governance pack",
      why: "Governance maturity evidence.",
      level: "required",
      category: "governance",
    },
  ],
  recommendedEvidence: [
    {
      evidenceType: "financial_statements",
      label: "Financial reporting package",
      why: "IPO financial narrative.",
      level: "recommended",
      category: "financial",
    },
    {
      evidenceType: "security_policies",
      label: "Compliance / security policies",
      why: "Sustained compliance posture.",
      level: "recommended",
      category: "security",
    },
    {
      evidenceType: "soc2",
      label: "SOC 2 / assurance reports",
      why: "External control assurance.",
      level: "recommended",
      category: "security",
    },
  ],
  reportSections: [
    "IPO readiness",
    "Controls",
    "Governance",
    "Audit & compliance",
    "Financial reporting",
    "Disclosure readiness",
    "Open gaps",
  ],
  recommendationOrdering: [
    { theme: "control", weight: 1.4, rationale: "IPO controls." },
    { theme: "governance", weight: 1.35, rationale: "Board maturity." },
    { theme: "audit", weight: 1.3, rationale: "Assurance path." },
    { theme: "compliance", weight: 1.25, rationale: "Ongoing posture." },
    { theme: "reporting", weight: 1.2, rationale: "Financial narrative." },
  ],
  recommendationDimensionWeights: {
    "dim-governance": 1.35,
    "dim-operations": 1.3,
    "dim-financial": 1.25,
    "dim-security": 1.2,
  },
  uploadCatalog: [
    {
      id: "upload-ipo-controls",
      label: "Financial controls documentation",
      evidenceCategory: "operations",
      why: "Core IPO control readiness.",
      level: "required",
      priority: 100,
      evidenceTypes: ["financial_controls"],
      questionsItCouldAnswer: ["q-ops-financial-controls"],
      expectedCoverageImpact: 0.15,
      applicableStages: ["Growth", "Scale", "Exit Ready"],
    },
    {
      id: "upload-ipo-governance",
      label: "Board governance pack",
      evidenceCategory: "governance",
      why: "Public-company board practices.",
      level: "required",
      priority: 98,
      evidenceTypes: ["board_minutes"],
      questionsItCouldAnswer: ["q-gov-cadence", "q-gov-board-approvals"],
      expectedCoverageImpact: 0.12,
      applicableStages: ["Growth", "Scale", "Exit Ready"],
    },
    {
      id: "upload-ipo-assurance",
      label: "SOC 2 / assurance reports",
      evidenceCategory: "security",
      why: "External compliance evidence.",
      level: "recommended",
      priority: 80,
      evidenceTypes: ["soc2"],
      questionsItCouldAnswer: ["q-sec-policies", "q-sec-critical-controls"],
      expectedCoverageImpact: 0.1,
      applicableStages: ["Growth", "Scale", "Exit Ready"],
    },
  ],
});
