import { COMPANY_LIFECYCLE_STAGES } from "@/lib/domain/company-classification";
import { definePlaybook } from "../base";

/** Run the Company — Protect / Grow / Operate / Prepare / Decide. */
export const runTheCompanyPlaybook = definePlaybook({
  id: "run-the-company",
  name: "Run the Company",
  objective:
    "Protect continuity, remove growth constraints, and prioritize highest operational impact.",
  successCriteria: [
    "Cash runway and burn are current and understood",
    "Customer concentration and retention risks are visible",
    "Operating KPIs and ownership are clear",
    "Material decisions have an evidence trail",
  ],
  focusAreas: ["Protect", "Grow", "Operate", "Prepare", "Decide"],
  applicableLifecycleStages: [...COMPANY_LIFECYCLE_STAGES],
  minCoveragePercent: 20,
  executiveSummaryGuidance: [
    "Lead with material downside (Protect), then growth constraints.",
    "Prefer highest expected operating impact over transaction readiness.",
  ],
  dimensionPriorities: [
    { dimensionId: "dim-financial", weight: 1, rationale: "Cash protects continuity." },
    { dimensionId: "dim-customer", weight: 0.9, rationale: "Retention bounds growth risk." },
    { dimensionId: "dim-people", weight: 0.85, rationale: "Execution capacity." },
    { dimensionId: "dim-operations", weight: 0.8, rationale: "Internal efficiency." },
    { dimensionId: "dim-governance", weight: 0.7, rationale: "Decision hygiene." },
  ],
  questionPriorities: [
    { questionId: "q-fin-runway-sufficient", weight: 1.5, rationale: "Protect cash." },
    { questionId: "q-fin-fund-operations", weight: 1.4, rationale: "Funding capacity." },
    { questionId: "q-ops-kpi-monitoring", weight: 1.4, rationale: "Operate with signal." },
    { questionId: "q-cust-concentration", weight: 1.3, rationale: "Protect revenue base." },
    { questionId: "q-cust-churn", weight: 1.2, rationale: "Grow sustainably." },
    { questionId: "q-ops-process-ownership", weight: 1.2, rationale: "Reduce drag." },
    { questionId: "q-people-key-person", weight: 1.2, rationale: "Key-person risk." },
    { questionId: "q-people-org-clarity", weight: 1.1, rationale: "Ownership clarity." },
    { questionId: "q-gov-board-approvals", weight: 1.0, rationale: "Prepare milestones." },
  ],
  requiredEvidence: [
    {
      evidenceType: "cash_runway",
      label: "Cash runway workbook",
      why: "Operating decisions need a hard floor.",
      level: "required",
      category: "financial",
    },
    {
      evidenceType: "financial_statements",
      label: "Financial statements",
      why: "Ground Protect and Operate lenses.",
      level: "required",
      category: "financial",
    },
  ],
  recommendedEvidence: [
    {
      evidenceType: "arr_snapshot",
      label: "Customer / ARR snapshot",
      why: "Supports Grow and concentration checks.",
      level: "recommended",
      category: "customer",
    },
    {
      evidenceType: "revenue_growth",
      label: "Financial forecast",
      why: "Forward operating plan.",
      level: "recommended",
      category: "financial",
    },
    {
      evidenceType: "org_chart",
      label: "Product roadmap / org clarity",
      why: "Clarifies ownership and next milestone prep.",
      level: "recommended",
      category: "operations",
    },
  ],
  reportSections: [
    "Protect",
    "Grow",
    "Operate",
    "Prepare",
    "Decide",
    "Evidence coverage",
    "Next actions",
  ],
  recommendationOrdering: [
    { theme: "protect", weight: 1.35, rationale: "Operational downside first." },
    { theme: "runway", weight: 1.3, rationale: "Cash continuity." },
    { theme: "grow", weight: 1.15, rationale: "Remove growth constraints." },
    { theme: "operate", weight: 1.1, rationale: "Reduce internal drag." },
    { theme: "prepare", weight: 1.0, rationale: "Milestone readiness." },
  ],
  recommendationDimensionWeights: {
    "dim-financial": 1.25,
    "dim-customer": 1.15,
    "dim-operations": 1.1,
    "dim-people": 1.05,
  },
  uploadCatalog: [
    {
      id: "upload-customer-metrics",
      label: "Customer metrics",
      evidenceCategory: "customer",
      why: "Grounds Grow and concentration risk.",
      level: "required",
      priority: 100,
      evidenceTypes: ["arr_snapshot", "revenue_growth"],
      questionsItCouldAnswer: ["q-cust-concentration", "q-cust-churn", "q-cust-nrr"],
      expectedCoverageImpact: 0.12,
      applicableStages: [
        "Early Revenue",
        "Product-Market Fit",
        "Growth",
        "Scale",
        "Exit Ready",
      ],
    },
    {
      id: "upload-financial-forecast",
      label: "Financial forecast",
      evidenceCategory: "financial",
      why: "Supports Protect and Operate planning.",
      level: "required",
      priority: 95,
      evidenceTypes: ["cash_runway", "financial_statements"],
      questionsItCouldAnswer: [
        "q-fin-runway-sufficient",
        "q-fin-fund-operations",
      ],
      expectedCoverageImpact: 0.15,
      applicableStages: [...COMPANY_LIFECYCLE_STAGES],
    },
    {
      id: "upload-product-roadmap",
      label: "Product roadmap",
      evidenceCategory: "operations",
      why: "Clarifies Prepare / Decide priorities.",
      level: "recommended",
      priority: 70,
      evidenceTypes: ["org_chart"],
      questionsItCouldAnswer: ["q-ops-process-ownership", "q-people-org-clarity"],
      expectedCoverageImpact: 0.08,
      applicableStages: [
        "Pre-product / MVP",
        "Early Revenue",
        "Product-Market Fit",
        "Growth",
        "Scale",
      ],
    },
  ],
});
